apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: testrms
  labels:
    app.kubernetes.io/name: testrms
spec:
  replicas: 2
  strategy:
    canary:
      stableService: testrms-stable
      canaryService: testrms-canary
      steps:
        - setWeight: 10
        - pause:
            duration: 5m
        - setWeight: 50
        - pause:
            duration: 5m
        - setWeight: 100
      analysis:
        templates:
          - templateName: testrms-success-rate
  selector:
    matchLabels:
      app.kubernetes.io/name: testrms
  template:
    metadata:
      labels:
        app.kubernetes.io/name: testrms
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: testrms
          image: ghcr.io/nadeem7sg/testrms:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: qa
            - name: RELEASE_ID
              value: rel_local_001
            - name: COMMIT_SHA
              value: local
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
