apiVersion: v1
kind: Service
metadata:
  name: testrms-stable
  labels:
    app.kubernetes.io/name: testrms
    app.kubernetes.io/role: stable
spec:
  selector:
    app.kubernetes.io/name: testrms
  ports:
    - name: http
      port: 80
      targetPort: http
